# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/optimizer_framework',
                'doc_host': 'https://redam94.github.io',
                'git_url': 'https://github.com/redam94/optimizer_framework',
                'lib_path': 'optimizer_framework'},
  'syms': {'optimizer_framework.core.exceptions': {}, 'optimizer_framework.core.interfaces': {}}}
