# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/optimizer-framework',
                'doc_host': 'https://redam94.github.io',
                'git_url': 'https://github.com/redam94/optimizer-framework',
                'lib_path': 'optimizer_framework'},
  'syms': {'optimizer_framework.core': {'optimizer_framework.core.foo': ('core.html#foo', 'optimizer_framework/core.py')}}}
